'use client';
import { useState } from 'react';
import { ArrowRight, BookOpen, Brain, Calculator, CheckCircle2, FileText, Menu, Target, Stethoscope, X, ShieldCheck } from 'lucide-react';
const features=[{icon:BookOpen,title:'Bank Soal',text:'Latihan soal per departemen, topik, dan tingkat kesulitan.'},{icon:Target,title:'CBT Simulator',text:'Simulasi dengan timer, navigasi soal, flag, dan hasil.'},{icon:Calculator,title:'Clinical Tools',text:'Kalkulator medis dan alat bantu klinis yang praktis.'},{icon:FileText,title:'Library',text:'Guideline, clinical pearls, cheat sheets, dan artikel.'}];
const departments=[['Cardiology','82%'],['Neurology','71%'],['Pediatrics','65%'],['Surgery','84%'],['Obgyn','76%']];
export default function Home(){const [mobileOpen,setMobileOpen]=useState(false);return <main>
<header className="nav"><div className="nav-inner"><div className="brand"><div className="brand-mark"><Stethoscope size={18}/></div><span>Dokter Jaga</span></div><nav className="desktop-nav"><a href="#belajar">Belajar</a><a href="#soal">Bank Soal</a><a href="#tools">Clinical Tools</a><a href="#library">Library</a><a href="#ppds">PPDS</a><a href="#pricing">Pricing</a></nav><div className="nav-actions"><button className="ghost">Masuk</button><button className="primary">Mulai Gratis</button><button className="menu" onClick={()=>setMobileOpen(v=>!v)} aria-label="menu">{mobileOpen?<X/>:<Menu/>}</button></div></div>{mobileOpen&&<div className="mobile-nav"><a href="#belajar">Belajar</a><a href="#soal">Bank Soal</a><a href="#tools">Clinical Tools</a><a href="#library">Library</a><a href="#ppds">PPDS</a><a href="#pricing">Pricing</a></div>}</header>
<section className="hero"><div className="hero-copy"><div className="eyebrow">Untuk dokter muda, sekarang dan nanti</div><h1>Belajar kedokteran.<br/>Latih <span>clinical reasoning.</span><br/>Siap menghadapi ujian.</h1><p>Bank soal, simulasi CBT, clinical tools, dan materi belajar untuk dokter muda dan calon peserta PPDS.</p><div className="cta-row"><button className="primary large">Mulai Belajar Gratis <ArrowRight size={18}/></button><button className="outline large">Lihat Bank Soal</button></div><div className="trust"><ShieldCheck size={16}/> Dibuat untuk belajar klinis yang lebih terarah.</div></div><div className="hero-visual"><div className="orb orb1"></div><div className="orb orb2"></div><div className="doctor-card"><div className="doctor-caption"><b>Better doctors.</b><span>Brighter tomorrow.</span></div><div className="doctor-avatar"><Stethoscope size={54}/></div></div><div className="floating-card"><div className="mini-icon"><Brain size={17}/></div><div><b>Daily target</b><span>18 / 20 questions</span></div></div></div></section>
<section className="stats"><div><b>5,000+</b><span>Soal berkualitas</span></div><div><b>15+</b><span>Departemen</span></div><div><b>CBT</b><span>Simulator</span></div><div><b>Tools</b><span>Clinical utilities</span></div></section>
<section id="belajar" className="section"><div className="section-head"><div><div className="eyebrow">One platform</div><h2>Semua yang kamu butuhkan, dalam satu tempat.</h2></div><a className="text-link" href="#soal">Explore platform <ArrowRight size={16}/></a></div><div className="feature-grid">{features.map(({icon:Icon,title,text})=><article className="feature" key={title}><div className="icon"><Icon size={22}/></div><h3>{title}</h3><p>{text}</p><a href="#soal">Mulai <ArrowRight size={15}/></a></article>)}</div></section>
<section id="soal" className="section soft"><div className="split"><div><div className="eyebrow">Adaptive practice</div><h2>Belajar berdasarkan apa yang masih perlu kamu kuasai.</h2><p className="lead">Setiap jawaban menjadi sinyal untuk rekomendasi soal berikutnya. Fokus pada topik yang belum kuat, bukan sekadar mengejar jumlah soal.</p><div className="bullets"><div><CheckCircle2 size={18}/><span>Study Mode dan Exam Mode</span></div><div><CheckCircle2 size={18}/><span>Clinical reasoning dalam pembahasan</span></div><div><CheckCircle2 size={18}/><span>Bookmark, history, dan weak-topic drill</span></div></div><button className="primary">Coba 10 Soal Gratis <ArrowRight size={17}/></button></div><div className="dashboard-card"><div className="dash-top"><div><span className="muted">UKMPPD Readiness</span><div className="readiness">78%</div></div><div className="target-icon"><Target size={25}/></div></div><div className="progress"><span></span></div>{departments.map(([name,val])=><div className="dept" key={name}><span>{name}</span><b>{val}</b></div>)}</div></div></section>
<section id="tools" className="section"><div className="tool-banner"><div><div className="eyebrow">Clinical tools</div><h2>Alat bantu klinis yang terasa seperti shortcut.</h2><p>Hitung, cek, dan kembali belajar tanpa berpindah platform.</p></div><button className="outline light">Buka Clinical Tools <ArrowRight size={17}/></button></div></section>
<footer className="footer"><div><div className="brand"><div className="brand-mark"><Stethoscope size={18}/></div><span>Dokter Jaga</span></div><p>Clinical learning platform untuk dokter Indonesia.</p></div><div className="footer-links"><a href="#belajar">Belajar</a><a href="#soal">Bank Soal</a><a href="#tools">Clinical Tools</a><a href="#ppds">PPDS</a></div></footer>
</main>}
