export type Question={id:number;department:string;topic:string;difficulty:string;question:string;options:string[];answer:number;explanation:string}
export const questions:Question[]=[
{id:1,department:'Cardiology',topic:'Acute Coronary Syndrome',difficulty:'Medium',question:'Pria 58 tahun datang dengan nyeri dada 2 jam. EKG menunjukkan ST elevasi pada V2–V4. Tindakan awal yang paling tepat adalah?',options:['Berikan aspirin dan aktivasi reperfusi segera','Tunggu troponin serial sebelum terapi','Berikan warfarin oral','Lakukan treadmill test','Berikan antibiotik empiris'],answer:0,explanation:'Gambaran konsisten dengan STEMI anterior. Aspirin segera dan strategi reperfusi adalah langkah penting; jangan menunda reperfusi untuk menunggu biomarker.'},
{id:2,department:'Neurology',topic:'Stroke',difficulty:'Easy',question:'Pasien tiba 90 menit setelah onset hemiparesis akut. CT kepala tidak menunjukkan perdarahan. Apa langkah berikutnya?',options:['Pertimbangkan trombolisis IV bila memenuhi kriteria','Pulang dan observasi di rumah','Mulai warfarin segera','Lakukan pungsi lumbal','Berikan steroid dosis tinggi'],answer:0,explanation:'Pada stroke iskemik akut dengan onset yang masih dalam jendela terapi, evaluasi kelayakan trombolisis IV dilakukan segera setelah perdarahan intrakranial disingkirkan.'},
{id:3,department:'Pediatrics',topic:'Pneumonia',difficulty:'Medium',question:'Anak 3 tahun dengan demam, takipnea, retraksi dinding dada, dan crackles fokal. Diagnosis paling mungkin?',options:['Pneumonia','BPPV','GERD','Croup','Otitis eksterna'],answer:0,explanation:'Demam, takipnea, retraksi, dan temuan paru fokal mendukung pneumonia.'},
{id:4,department:'Surgery',topic:'Acute Abdomen',difficulty:'Medium',question:'Nyeri berpindah dari periumbilikal ke kuadran kanan bawah disertai anoreksia dan mual paling khas untuk?',options:['Apendisitis akut','Pankreatitis','Kolesistitis','Divertikulitis sigmoid','Gastroenteritis'],answer:0,explanation:'Pola migrasi nyeri menuju kuadran kanan bawah disertai gejala gastrointestinal merupakan gambaran klasik apendisitis akut.'},
{id:5,department:'Obgyn',topic:'Eclampsia',difficulty:'Hard',question:'Ibu hamil 36 minggu mengalami kejang tonik-klonik dengan tekanan darah 170/110 mmHg. Prioritas terapi farmakologis untuk mencegah kejang berulang?',options:['Magnesium sulfat','Diazepam oral','Aspirin dosis rendah','Furosemide IV sebagai terapi tunggal','Metformin'],answer:0,explanation:'Magnesium sulfat merupakan terapi utama untuk pencegahan dan tata laksana kejang pada eklampsia.'},
{id:6,department:'Internal Medicine',topic:'Diabetes Mellitus',difficulty:'Easy',question:'Pemeriksaan yang paling sering digunakan untuk menilai kontrol glikemik jangka panjang pada DM?',options:['HbA1c','D-dimer','Troponin','CRP','Amilase'],answer:0,explanation:'HbA1c merefleksikan rerata glikemia sekitar 2–3 bulan terakhir dan umum digunakan untuk monitoring kontrol diabetes.'},
{id:7,department:'Emergency Medicine',topic:'Sepsis',difficulty:'Hard',question:'Pasien dengan infeksi berat mengalami hipotensi persisten setelah resusitasi cairan awal. Vasopresor pilihan pertama umumnya?',options:['Norepinefrin','Dobutamin sebagai satu-satunya vasopresor','Furosemide','Nitrogliserin','Atropin'],answer:0,explanation:'Norepinefrin merupakan vasopresor pilihan pertama pada syok septik persisten setelah resusitasi cairan yang adekuat.'},
{id:8,department:'Pulmonology',topic:'Asthma',difficulty:'Medium',question:'Pasien asma mengalami wheezing dan sesak akut. Obat bronkodilator kerja cepat yang lazim digunakan untuk pereda gejala adalah?',options:['SABA inhalasi','Warfarin','Digoksin','Levotiroksin','Metotreksat'],answer:0,explanation:'Short-acting beta-2 agonist inhalasi dapat digunakan sebagai bronkodilator kerja cepat untuk meredakan bronkospasme akut.'}
]
