'use client';
import {useMemo,useState} from 'react'; import {Bookmark,CheckCircle2,Filter,Search,Star} from 'lucide-react'; import {Shell,PageHero} from '../components';
const qs=[
 {id:1,dept:'Cardiology',topic:'ACS',diff:'Sedang',q:'Pria 65 tahun datang dengan nyeri dada akut menjalar ke lengan kiri. EKG menunjukkan ST elevasi pada II, III, aVF. Diagnosis paling mungkin?',opts:['STEMI inferior','NSTEMI','Angina tidak stabil','Perikarditis','Diseksi aorta'],ans:0,why:'ST elevasi pada II, III, aVF konsisten dengan STEMI inferior.'},
 {id:2,dept:'Neurology',topic:'Stroke',diff:'Sulit',q:'Wanita 58 tahun mendadak mengalami hemiparesis kanan dan afasia. Onset 70 menit lalu. Langkah berikutnya?',opts:['CT kepala non-kontras segera','MRI 24 jam kemudian','Aspirin sebelum imaging','Observasi','Lumbar puncture'],ans:0,why:'Pada defisit neurologis akut dengan onset jelas, CT non-kontras dilakukan segera untuk menyingkirkan perdarahan.'},
 {id:3,dept:'Pediatrics',topic:'Emergency',diff:'Mudah',q:'Anak 2 tahun dengan diare cair, mata cekung, haus, dan masih dapat minum. Rehidrasi awal?',opts:['ORS oral','Furosemide','Dextrose 5% saja','Restriksi cairan','Antibiotik rutin'],ans:0,why:'Tanda dehidrasi tanpa syok ditangani dengan oral rehydration solution.'},
 {id:4,dept:'Surgery',topic:'Acute abdomen',diff:'Sedang',q:'Nyeri berpindah dari periumbilikal ke kuadran kanan bawah disertai anoreksia dan demam ringan. Diagnosis paling mungkin?',opts:['Apendisitis akut','Kolesistitis','Pankreatitis','Gastritis','IBS'],ans:0,why:'Pola migrasi nyeri ke kuadran kanan bawah dengan anoreksia khas apendisitis.'}
];
export default function BankSoal(){const [search,setSearch]=useState('');const [dept,setDept]=useState('Semua');const [selected,setSelected]=useState<Record<number,number>>({});const [show,setShow]=useState<number|null>(null);const list=useMemo(()=>qs.filter(x=>(dept==='Semua'||x.dept===dept)&&(`${x.q} ${x.topic} ${x.dept}`.toLowerCase().includes(search.toLowerCase()))),[search,dept]);return <Shell><PageHero eyebrow="QUESTION BANK" title="Bank Soal" description="Latihan berbasis kasus dengan filter, pembahasan, bookmark, dan clinical reasoning."/><main className="container page-content"><div className="toolbar"><div className="searchbox"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari diagnosis, topik, atau kata kunci..."/></div><div className="filters"><Filter size={17}/><select value={dept} onChange={e=>setDept(e.target.value)}><option>Semua</option><option>Cardiology</option><option>Neurology</option><option>Pediatrics</option><option>Surgery</option></select></div></div><div className="question-layout"><div>{list.map(item=><article className="question-card" key={item.id}><div className="question-meta"><span className="tag">{item.dept}</span><span className="tag subtle">{item.topic}</span><span className="difficulty">{item.diff}</span><Bookmark size={17}/></div><h3>Soal {item.id}. {item.q}</h3><div className="options">{item.opts.map((o,i)=><button key={o} className={selected[item.id]===i?'option selected':'option'} onClick={()=>{setSelected({...selected,[item.id]:i});setShow(item.id)}}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div>{show===item.id&&<div className="explain"><div><CheckCircle2 size={18}/> Jawaban: <b>{String.fromCharCode(65+item.ans)}</b></div><p>{item.why}</p></div>}</article>)}</div><aside className="side-card"><Star size={20}/><h3>Study Progress</h3><b>12 / 20</b><p>soal hari ini</p><div className="progress"><span style={{width:'60%'}}/></div><small>Target harian 20 soal</small></aside></div></main></Shell>}
